// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwURZvyXz8fDsq1w-kba7WIPQTiTs3omk',
    appId: '1:395959080272:web:1893710436b05c734cc855',
    messagingSenderId: '395959080272',
    projectId: 'bookwise-d67aa',
    authDomain: 'bookwise-d67aa.firebaseapp.com',
    storageBucket: 'bookwise-d67aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT7dBkUJ93OOUglWdraG9Nczi8eAsmgq0',
    appId: '1:395959080272:android:2bad6b74ae53d3b24cc855',
    messagingSenderId: '395959080272',
    projectId: 'bookwise-d67aa',
    storageBucket: 'bookwise-d67aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQVmFWa4hhbNr_pSPnM1fwo3YztFwobo',
    appId: '1:395959080272:ios:eeb43ccb0d31900a4cc855',
    messagingSenderId: '395959080272',
    projectId: 'bookwise-d67aa',
    storageBucket: 'bookwise-d67aa.appspot.com',
    iosBundleId: 'com.example.bookwiseStaff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQVmFWa4hhbNr_pSPnM1fwo3YztFwobo',
    appId: '1:395959080272:ios:eeb43ccb0d31900a4cc855',
    messagingSenderId: '395959080272',
    projectId: 'bookwise-d67aa',
    storageBucket: 'bookwise-d67aa.appspot.com',
    iosBundleId: 'com.example.bookwiseStaff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwURZvyXz8fDsq1w-kba7WIPQTiTs3omk',
    appId: '1:395959080272:web:91a453c17a6453954cc855',
    messagingSenderId: '395959080272',
    projectId: 'bookwise-d67aa',
    authDomain: 'bookwise-d67aa.firebaseapp.com',
    storageBucket: 'bookwise-d67aa.appspot.com',
  );

}